# fly.toml

app = "toto-final"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# ADD THIS SECTION IF NOT PRESENT:
[[mounts]]
  source = "toto_data"           # The volume name you created
  destination = "/data"          # Where it will be mounted in the container
